controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Article;
use app\models\Category;
use app\models\LoginForm;
use app\models\ContactForm;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
      $data = Article::getAll(2);

        return $this->render('index',[
          'articles'=>$data['articles'],
          'pagination'=> $data['pagination'],
        ]);
    }

    public function actionView($id)
    {
      $article = Article::findOne($id);
      return $this->render('single',[
        'article' => $article,
      ]);
    }

    public function actionCategory($id)
    {
      $data = Category::getArticlesByCategory($id);
      return $this->render('category',[
        'articles' => $data['articles'],
        'pagination' => $data['pagination']
      ]);
    }

    public function actionTag($id)
    {
      $data = Category::getArticlesByTag($id);
      return $this->render('tag',[
        'articles' => $data['articles'],
        'pagination' => $data['pagination']
      ]);
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/category.php
<?php
use yii\helpers\Url;
use yii\widgets\LinkPager;
?>
<?php

foreach($articles as $article):?>
    <article class="post post-list">
    <div class="row">
        <div class="col-md-6">
            <div class="post-thumb">
                <a href="<?= Url::toRoute(['site/view','id'=>$article->id]);?>"><img src="<?= $article->getImage();?>" alt="" class="pull-left"></a>

                <a href="<?= Url::toRoute(['site/view','id'=>$article->id]);?>" class="post-thumb-overlay text-center">
                    <div class="text-uppercase text-center">View Post</div>
                </a>
            </div>
        </div>
        <div class="col-md-6">
            <div class="post-content">
                <header class="entry-header text-uppercase">
                    <h6><a href="<?= Url::toRoute(['site/category','id'=>$article->category->id]);?>"> <?= $article->category->title?></a></h6>

                    <h1 class="entry-title"><a href="<?= Url::toRoute(['site/view','id'=>$article->id]);?>"><?= $article->title; ?></a></h1>
                </header>
                <div class="entry-content">
                    <p><?= $article->description?>
                    </p>
                </div>
                <div class="social-share">
                    <span class="social-share-title pull-left text-capitalize">By article->author->name; On <?= $article->getDate();?></span>

                </div>
            </div>
        </div>
    </div>
</article>
<?php endforeach;?>

<?php
echo LinkPager::widget([
    'pagination' => $pagination,
]);
?>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<div class="row">
    <div class="col-sm-12 st-content">
        <div id="primary" class="content-area padding-content white-color">
            <main id="main" class="site-main" role="main">

                <section class="error-404 not-found text-center">
                    <h1 class="404">404</h1>

                    <p class="lead">Sorry, we could not found the page you are looking for!</p>

                    <div class="row">
                        <div class="col-sm-4 col-sm-offset-4">
                            <form role="search" method="get" id="searchform" action="#">
                                <div>
                                    <input type="text" placeholder="Search and hit enter..." name="s" id="s"/>
                                </div>
                            </form>
                            <p class="go-back-home"><a href="index.html">
                                Back to Home Page</a></p>
                        </div>
                    </div>

                </section><!-- .error-404 -->

            </main><!-- #main -->
        </div><!-- #primary -->
    </div>
</div>

views/site/index.php
<?php
use yii\helpers\Url;
use yii\widgets\LinkPager;
?>
<?php foreach ($articles as $article): ?>
    <article class="post">
        <div class="post-thumb">
            <img src="<?= $article->getImage();?>" alt="">
            <a href="<?= Url::toRoute(['site/view', 'id'=>$article->id]) ?>" class="post-thumb-overlay text-center">
                <div class="text-uppercase text-center">View Post</div>
            </a>
        </div>
        <div class="post-content">
            <header class="entry-header text-center text-uppercase">
                  <h6><a href="<?= Url::toRoute(['site/category','id'=>$article->category->id])?>"> <?= $article->category->title; ?></a></h6>
                  <?php foreach($article->tags as $tag) : ?>
                    <a href="<?= Url::toRoute(['site/tag','id'=>$tag->id])?>"> <?= $tag->title; ?> </a>
                  <?php endforeach; ?>
                <h1 class="entry-title"><a href="<?= Url::toRoute(['site/view', 'id'=>$article->id]) ?>"><?= $article->title; ?></a></h1>
            </header>
            <div class="entry-content">
                <p><?= $article->description;?></p>
                <div class="btn-continue-reading text-center text-uppercase">
                    <a href="<?= Url::toRoute(['site/view', 'id'=>$article->id]) ?>" class="more-link">Continue Reading</a>
                </div>
            </div>
            <div class="social-share">
                <span class="social-share-title pull-left text-capitalize">By <a href="#">Rubel</a> <?= $article->getDate(); ?></span>
                <ul class="text-center pull-right">
                    <li><a class="s-facebook" href="#"><i class="fa fa-eye"></i></a></li><?= (int) $article->viewed; ?>
                </ul>
            </div>
        </div>
    </article>
<?php endforeach; ?>
<?php
echo LinkPager::widget([
   'pagination' => $pagination,
]);
?>

views/site/single.php
<?php
use yii\helpers\Url;
?>
<article class="post">
    <div class="post-thumb">
        <img src="<?= $article->getImage(); ?>" alt="">
    </div>
    <div class="post-content">
        <header class="entry-header text-center text-uppercase">
            <h6><a href="<?= Url::toRoute(['site/category','id'=>$article->category->id]);?>"> <?= $article->category->title?></a></h6>
            <h1 class="entry-title"><?= $article->title ?></h1>
        </header>
        <div class="entry-content">
            <?= $article->content ?>
        </div>
        <div class="decoration">

          <div class="tags">
            <?php foreach($article->tags as $tag) : ?>
              <a href="<?= Url::toRoute(['site/tag','id'=>$tag->id])?>"  class="btn btn-default"> <?= $tag->title; ?> </a>
            <?php endforeach; ?>
        </div>

        <div class="social-share">
      <span class="social-share-title pull-left text-capitalize">By Rubel On <?= $article->getDate(); ?> </span>
            <ul class="text-center pull-right">
                <li><a class="s-facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a class="s-twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a class="s-google-plus" href="#"><i class="fa fa-google-plus"></i></a></li>
                <li><a class="s-linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
                <li><a class="s-instagram" href="#"><i class="fa fa-instagram"></i></a></li>
            </ul>
        </div>
    </div>
</article>
<div class="top-comment"><!--top comment-->
    <img src="/public/images/comment.jpg" class="pull-left img-circle" alt="">
    <h4>Rubel Miah</h4>

    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy hello ro mod tempor
        invidunt ut labore et dolore magna aliquyam erat.</p>
</div><!--top comment end-->
<div class="row"><!--blog next previous-->
    <div class="col-md-6">
        <div class="single-blog-box">
            <a href="#">
                <img src="/public/images/blog-next.jpg" alt="">

                <div class="overlay">

                    <div class="promo-text">
                        <p><i class=" pull-left fa fa-angle-left"></i></p>
                        <h5>Rubel is doing Cherry theme</h5>
                    </div>
                </div>


            </a>
        </div>
    </div>
    <div class="col-md-6">
        <div class="single-blog-box">
            <a href="#">
                <img src="/public/images/blog-next.jpg" alt="">

                <div class="overlay">
                    <div class="promo-text">
                        <p><i class=" pull-right fa fa-angle-right"></i></p>
                        <h5>Rubel is doing Cherry theme</h5>

                    </div>
                </div>
            </a>
        </div>
    </div>
</div><!--blog next previous end-->
<div class="related-post-carousel"><!--related post carousel-->
    <div class="related-heading">
        <h4>You might also like</h4>
    </div>
    <div class="items">
        <div class="single-item">
            <a href="#">
                <img src="/public/images/related-post-1.jpg" alt="">

                <p>Just Wondering at Beach</p>
            </a>
        </div>


        <div class="single-item">
            <a href="#">
                <img src="/public/images/related-post-2.jpg" alt="">

                <p>Just Wondering at Beach</p>
            </a>
        </div>


        <div class="single-item">
            <a href="#">
                <img src="/public/images/related-post-3.jpg" alt="">

                <p>Just Wondering at Beach</p>
            </a>
        </div>


        <div class="single-item">
            <a href="#">
                <img src="/public/images/related-post-1.jpg" alt="">

                <p>Just Wondering at Beach</p>
            </a>
        </div>

        <div class="single-item">
            <a href="#">
                <img src="/public/images/related-post-2.jpg" alt="">

                <p>Just Wondering at Beach</p>
            </a>
        </div>


        <div class="single-item">
            <a href="#">
                <img src="/public/images/related-post-3.jpg" alt="">

                <p>Just Wondering at Beach</p>
            </a>
        </div>
    </div>
</div><!--related post carousel-->
<div class="bottom-comment"><!--bottom comment-->
    <h4>3 comments</h4>

    <div class="comment-img">
        <img class="img-circle" src="/public/images/comment-img.jpg" alt="">
    </div>

    <div class="comment-text">
        <a href="#" class="replay btn pull-right"> Replay</a>
        <h5>Rubel Miah</h5>

        <p class="comment-date">
            December, 02, 2015 at 5:57 PM
        </p>


        <p class="para">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed
            diam nonumy
            eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
            voluptua. At vero eos et cusam et justo duo dolores et ea rebum.</p>
    </div>
</div>
<!-- end bottom comment-->


<div class="leave-comment"><!--leave comment-->
    <h4>Leave a reply</h4>


    <form class="form-horizontal contact-form" role="form" method="post" action="#">
        <div class="form-group">
            <div class="col-md-6">
                <input type="text" class="form-control" id="name" name="name" placeholder="Name">
            </div>
            <div class="col-md-6">
                <input type="email" class="form-control" id="email" name="email"
                       placeholder="Email">
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <input type="text" class="form-control" id="subject" name="subject"
                       placeholder="Website url">
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
    <textarea class="form-control" rows="6" name="message"
                                  placeholder="Write Massage"></textarea>
            </div>
        </div>
        <a href="#" class="btn send-btn">Post Comment</a>
    </form>
</div><!--end leave comment-->

views/site/tag.php
<?php
use yii\helpers\Url;
use yii\widgets\LinkPager;
?>
<?php

foreach($articles as $article):?>
    <article class="post post-list">
    <div class="row">
        <div class="col-md-6">
            <div class="post-thumb">
                <a href="<?= Url::toRoute(['site/view','id'=>$article->id]);?>"><img src="<?= $article->getImage();?>" alt="" class="pull-left"></a>

                <a href="<?= Url::toRoute(['site/view','id'=>$article->id]);?>" class="post-thumb-overlay text-center">
                    <div class="text-uppercase text-center">View Post</div>
                </a>
            </div>
        </div>
        <div class="col-md-6">
            <div class="post-content">
                <header class="entry-header text-uppercase">
                    <h6><a href="<?= Url::toRoute(['site/category','id'=>$article->category->id]);?>"> <?= $article->category->title?></a></h6>

                    <h1 class="entry-title"><a href="<?= Url::toRoute(['site/view','id'=>$article->id]);?>"><?= $article->title; ?></a></h1>
                </header>
                <div class="entry-content">
                    <p><?= $article->description?>
                    </p>
                </div>
                <div class="social-share">
                    <span class="social-share-title pull-left text-capitalize">By article->author->name; On <?= $article->getDate();?></span>

                </div>
            </div>
        </div>
    </div>
</article>
<?php endforeach;?>

<?php
echo LinkPager::widget([
    'pagination' => $pagination,
]);
?>